require 'ffi-compiler/compile_task'

FFI::Compiler::CompileTask.new('webp_ffi') do |c|
  c.have_header?('stdio.h', '/usr/local/include')
  c.have_func?('puts')
  c.have_library?('z')
  # webp
  c.have_header?('decode.h', '/usr/local/include')
  c.have_header?('encode.h', '/usr/local/include')
  c.have_func?('WebPDecoderConfig')
  c.have_func?('WebPGetInfo')
  c.have_library?('webp')
  # compiler flags
  c.cflags << "-arch x86_64" if c.platform.mac?
  c.ldflags << "-arch x86_64" if c.platform.mac?
end
